package: openbabel

build_targets: conda

platform:
  - linux-64

engine:
  - python=2.7
  - python=3.4
  - python=3.5


before_script:
  - conda update --all --yes
  - conda config --add channels mwojcikowski
  
script: conda build .
