
package:
    name: openbabel
    version: 2.4.0

source:
    fn: openbabel-2-4-0.zip
    url: https://github.com/openbabel/openbabel/archive/openbabel-2-4-0.zip
    sha1: 822ceadb66316b281ecfcbb37e1c7227634b909d

    patches:
        - fix_library_path_search.diff
        - fix_data_path.diff
        - fix_babel_test_paths.diff

build:
    number: 1
    detect_binary_files_with_prefix: true

requirements:
    build:
        - gcc     # [linux]
        - llvm    # [osx]
        - cmake
        - zlib
        - swig
        - eigen
        - bzip2
        - python
        - libxml2
    run:
        - python
        - libgcc  # [linux]
        - zlib
        - libxml2
test:
  imports:
    - openbabel
    - pybel
  commands:
    - obabel --help
    - obabel -:"c1ccccc1" --gen3d -omol2

about:
    home: http://www.openbabel.org/
    license: GPLv2
    summary: "A chemical toolbox designed to speak the many languages of chemical data"
